var CONFIG_NAMES = {
    en: {
        "playerStartMass": strData(null, "Start mass of the player cell"),
        "playerMaxCells": strData(null, "Max cells the player is allowed to have"),
        "playerSpeed": strData(null, "Player speed multiplier (1=normal speed, 2=twice faster)"),
        "playerDecayRate": strData(null, "Amount of size lost per second"),
        "playerRecombineTime": strData(null, "Base time in seconds before a cell is allowed to recombine"),
        "ejectSize": strData(null, "Eject size"),
        "ejectSizeLoss": strData(null, "Eject size which will be substracted from player cell"),
        "ejectDistance": strData(null, "How far your eject goes after throw"),
        "ejectCooldown": strData(null, "Tick count until a player can eject mass again (1 tick = 40 ms)"),
        "foodMinSize": strData(null, "Minimum food size"),
        "foodMinAmount": strData(null, "Minimum food cells on the map"),
        "virusMinSize": strData(null, "Minimum virus size"),
        "virusMinAmount": strData(null, "Minimum number of viruses on the map"),
        "speedBoosterMinAmount": strData(null, "Amount of speed PowerUps"),
        "speedBoosterTime": strData(null, "How much time it will work"),
        "speedBoosterValue": strData(null, "Multiplyer of speed (1.5 = 50% faster, 0.5 = 50% slower"),
        "speedBoosterSize": strData(null, "How big PowerUp is"),
        "mergeBoosterMinAmount": strData(null, "Amount of merge PowerUps"),
        "mergeBoosterTime": strData(null, "How much time it will work"),
        "mergeBoosterValue": strData(null, "Multiplyer of recombine time (0.5 = 50% faster, 1.5 = 50% slower)"),
        "mergeBoosterSize": strData(null, "How big PowerUp is"),
        "virusBoosterMinAmount": strData(null, "Amount of virus PowerUps"),
        "virusBoosterTime": strData(null, "How much time it will work"),
        "virusBoosterSize": strData(null, "How big PowerUp is"),
        "sizeBoosterMinAmount": strData(null, "Amount of size PowerUps"),
        "sizeBoosterTime": strData(null, "How much time it will work"),
    },
    ru: {
        "playerStartMass": strData("стартМасса", "Стартовая масса шара игрока"),
        "playerMaxCells": strData("максКолШаров", "Максимальное количество шаров которое игрок может иметь"),
        "playerSpeed": strData("скорДвижИгрока", "Множитель скорости игрока (1=стандартная, 2=в два раза быстрее)"),
        "playerDecayRate": strData("скорПотериМассы", "Скорость потерми массы игроком"),
        "playerRecombineTime": strData("скорСоедШаров", "Базовое время в секунда перед тем как шару позволяется соедениться"),
        "ejectSize": strData("размЕджекта", "Размер еджекта"),
        "ejectSizeLoss": strData("ушербЕджекта", "  Eject size which will be substracted from player cell"),
        "ejectDistance": strData("дальнЕджекта", "Как далеко летит еджект после бросания"),
        "ejectCooldown": strData("откактЕджекта", "Кол-во тиков до того как игрок может опять бросать еджект (1 тик = 40 мс)"),
        "foodMinSize": strData("минРазмЕды", "Минимальный размер еды"),
        "foodMinAmount": strData("минКолЕды", "Минимальное кол-во еды на карте"),
        "virusMinSize": strData("минРазмВируса", "Минимальный размер вируса"),
        "virusMinAmount": strData("минКолВирусов", "Минимальное количество вирусов на карте"),
        "speedBoosterMinAmount": strData("минКолБустовСкор", "Кол-во бустеров(поверапов) скорости"),
        "speedBoosterTime": strData("длитДейстБустовСкор", "Длительность действия бустера скорости"),
        "speedBoosterValue": strData("силаБустаСкорости", "Множитель скорости (1.5 = на 50% быстрее, 0.5 = на 50% медленнее"),
        "speedBoosterSize": strData("размерБустаСкорости", "На сколько большой бустер скорости"),
        "mergeBoosterMinAmount": strData("минКолБустовСлияния", "Кол-во бустеров слияния/соединения"),
        "mergeBoosterTime": strData("длитДейстБустовСлияния", "Длительность действия бустера слияния"),
        "mergeBoosterValue": strData("силаБустаСлияния", "Множитель задержки соединения (1.5 = на 50% быстрее, 0.5 = на 50% медленнее"),
        "mergeBoosterSize": strData("размерБустаСлияния", "На сколько большой бустер слияния"),
        "virusBoosterMinAmount": strData("минКолБустовВируса", "Кол-во бустеров вируса (игрок становится колючкой)"),
        "virusBoosterTime": strData("длитДейстБустовВируса", "Длительность действия бустеров вируса (игрок становится колючкой)"),
        "virusBoosterSize": strData("размерБустаВируса", "На сколько большой бустер вируса"),
        "sizeBoosterMinAmount": strData("минКолБустовРазмера", "Кол-во бустеров размера (игрок растет сам по себе)"),
        "sizeBoosterTime": strData("длитДейстБустовРазмера", "Длительность действия бустера размера (игрок растет сам по себе)"),
    },
    // uk: {},
    // ar: {},
    // es: {},
    // fr: {},
    // tr: {},
    // pt: {},
    // de: {},
}

function strData(name, desc) {
    return {
        n: name,
        d: desc
    }
}

module.exports = CONFIG_NAMES;