var CONFIG_NAMES = {
    en: {
        "playerStartMass": strData(null, "Start mass of the player cell"),
        "playerMaxCells": strData(null, "Max cells the player is allowed to have"),
        "playerSpeed": strData(null, "Player speed multiplier (1=normal speed, 2=twice faster)"),
        "playerDecayRate": strData(null, "Amount of size lost per second"),
        "playerRecombineTime": strData(null, "Base time in seconds before a cell is allowed to recombine"),
        "ejectSize": strData(null, "Eject size"),
        "ejectSizeLoss": strData(null, "Eject size which will be substracted from player cell"),
        "ejectDistance": strData(null, "How far your eject goes after throw"),
        "ejectCooldown": strData(null, "Tick count until a player can eject mass again (1 tick = 40 ms)"),
        "foodMinSize": strData(null, "Minimum food size"),
        "foodMinAmount": strData(null, "Minimum food cells on the map"),
        "virusMinSize": strData(null, "Minimum virus size"),
        "virusMinAmount": strData(null, "Minimum number of viruses on the map"),
        "speedBoosterMinAmount": strData(null, "Amount of speed PowerUps"),
        "speedBoosterTime": strData(null, "How much time it will work"),
        "speedBoosterValue": strData(null, "Multiplyer of speed (1.5 = 50% faster, 0.5 = 50% slower"),
        "speedBoosterSize": strData(null, "How big PowerUp is"),
        "mergeBoosterMinAmount": strData(null, "Amount of merge PowerUps"),
        "mergeBoosterTime": strData(null, "How much time it will work"),
        "mergeBoosterValue": strData(null, "Multiplyer of recombine time (0.5 = 50% faster, 1.5 = 50% slower)"),
        "mergeBoosterSize": strData(null, "How big PowerUp is"),
        "virusBoosterMinAmount": strData(null, "Amount of virus PowerUps"),
        "virusBoosterTime": strData(null, "How much time it will work"),
        "virusBoosterSize": strData(null, "How big PowerUp is"),
        "sizeBoosterMinAmount": strData(null, "Amount of size PowerUps"),
        "sizeBoosterTime": strData(null, "How much time it will work"),
    },
    ru: {
        "playerStartMass": strData("стартМасса", "Стартовая масса шара игрока"),
        "playerMaxCells": strData("максКолШаров", "Максимальное количество шаров которое игрок может иметь"),
        "playerSpeed": strData("скорДвижИгрока", "Множитель скорости игрока (1=стандартная, 2=в два раза быстрее)"),
        "playerDecayRate": strData("скорПотериМассы", "Скорость потерми массы игроком"),
        "playerRecombineTime": strData("скорСоедШаров", "Базовое время в секунда перед тем как шару позволяется соедениться"),
        "ejectSize": strData("размЕджекта", "Размер еджекта"),
        "ejectSizeLoss": strData("ушербЕджекта", "  Eject size which will be substracted from player cell"),
        "ejectDistance": strData("дальнЕджекта", "Как далеко летит еджект после бросания"),
        "ejectCooldown": strData("откактЕджекта", "Кол-во тиков до того как игрок может опять бросать еджект (1 тик = 40 мс)"),
        "foodMinSize": strData("минРазмЕды", "Минимальный размер еды"),
        "foodMinAmount": strData("минКолЕды", "Минимальное кол-во еды на карте"),
        "virusMinSize": strData("минРазмВируса", "Минимальный размер вируса"),
        "virusMinAmount": strData("минКолВирусов", "Минимальное количество вирусов на карте"),
        "speedBoosterMinAmount": strData("минКолБустовСкор", "Кол-во бустеров(поверапов) скорости"),
        "speedBoosterTime": strData("длитДейстБустовСкор", "Длительность действия бустера скорости"),
        "speedBoosterValue": strData("силаБустаСкорости", "Множитель скорости (1.5 = на 50% быстрее, 0.5 = на 50% медленнее"),
        "speedBoosterSize": strData("размерБустаСкорости", "На сколько большой бустер скорости"),
        "mergeBoosterMinAmount": strData("минКолБустовСлияния", "Кол-во бустеров слияния/соединения"),
        "mergeBoosterTime": strData("длитДейстБустовСлияния", "Длительность действия бустера слияния"),
        "mergeBoosterValue": strData("силаБустаСлияния", "Множитель задержки соединения (1.5 = на 50% быстрее, 0.5 = на 50% медленнее"),
        "mergeBoosterSize": strData("размерБустаСлияния", "На сколько большой бустер слияния"),
        "virusBoosterMinAmount": strData("минКолБустовВируса", "Кол-во бустеров вируса (игрок становится колючкой)"),
        "virusBoosterTime": strData("длитДейстБустовВируса", "Длительность действия бустеров вируса (игрок становится колючкой)"),
        "virusBoosterSize": strData("размерБустаВируса", "На сколько большой бустер вируса"),
        "sizeBoosterMinAmount": strData("минКолБустовРазмера", "Кол-во бустеров размера (игрок растет сам по себе)"),
        "sizeBoosterTime": strData("длитДейстБустовРазмера", "Длительность действия бустера размера (игрок растет сам по себе)"),
    },
    // uk: {},
    ar: {
        "playerStartMass": strData(null, "حجم اللاعب عند بدايته اللعب"),
        "playerMaxCells": strData(null, "الحد الأقصى للقطع اللتي يمكن للاعب ان يملكها"),
        "playerSpeed": strData(null, "سرعة اللاعب المضاعفه (1=normal speed, 2=twice faster)"),
        "playerDecayRate": strData(null, "كمية الحجم اللتى سيخسرها اللاعب خلال ثانيه واحده"),
        "playerRecombineTime": strData(null, "الوقت الأساسي بالثواني المحدده قبل اتحاد القطع"),
        "ejectSize": strData(null, "حجم نقاط الدعم"),
        "ejectSizeLoss": strData(null, "حجم نقاط الدعم الَّتي سيطرحها اللاعب  من قِطعَتِه"),
        "ejectDistance": strData(null, "المسافه اللتي ستقطعها نقاط الدعم الخاصّه باللاعب بعد طرحها من قطعته"),
        "ejectCooldown": strData(null, "فرق الوقت تيك  بين كل نقطة دعم  تطرحها قطعك و نقطة الدعم الّتي تليها  (1 tick = 40 ms)"),
        "foodMinSize": strData(null, " جحم الطعام المبعثر على الخريطه"),
        "foodMinAmount": strData(null, "عدد قطع الطعام المبعثر على الخريطه"),
        "virusMinSize": strData(null, "الحد الأدنى لجحم الشوكه"),
        "virusMinAmount": strData(null, "العدد الأدنى للأشواك "),
        "speedBoosterMinAmount": strData(null, "العدد الادنى لمعززات السرعه"),
        "speedBoosterTime": strData(null, "الوقت المخصص لمعزز السرعه"),
        "speedBoosterValue": strData(null, "مضاعفة معزز السرعه (1.5 = 50% faster, 0.5 = 50% slower")"
        "speedBoosterSize": strData(null, "حجم معزز السرعه"),
        "mergeBoosterMinAmount": strData(null, "عدد معززات التجمع"),
        "mergeBoosterTime": strData(null, "الوقت المخصص لمعزز التجمع"),
        "mergeBoosterValue": strData(null, "مضاعفة  وقت تجمع القطع (0.5 = 50% faster, 1.5 = 50% slower)"),
        "mergeBoosterSize": strData(null, "حجم معزز التجمع"),
        "virusBoosterMinAmount": strData(null, "عدد معززات الشوكه"),
        "virusBoosterTime": strData(null, "الوقت المخصص لمعزز الشوكه"),
        "virusBoosterSize": strData(null, "حجم معزز الشوكه"),
        "sizeBoosterMinAmount": strData(null, "عدد معززات الحجم"),
        "sizeBoosterTime": strData(null, "الوقت المخصص لمعزز الحجم"),
    },
    es: {
        "playerStartMass": strData(null, "Masa inicial de jugadores"),
        "playerMaxCells": strData(null, "Máximo de celdas que puede tener un jugador"),
        "playerSpeed": strData(null, "Velocidad para multiplicar (1=velocidad normal, 2=2x más rápido)"),
        "playerDecayRate": strData(null, "Tamaño perdido por segundo"),
        "playerRecombineTime": strData(null, "Tiempo base para unirse"),
        "ejectSize": strData(null, "Tamaño de eyección"),
        "ejectSizeLoss": strData(null, "Tamaño de eyección que se eliminará de la celdras de los jugadores"),
        "ejectDistance": strData(null, "Hasta dónde llega la eyección después de dividirse"),
        "ejectCooldown": strData(null, "Cronómetro hasta que un jugador expulse masa de nuevo (1 tick = 40 ms)"),
        "foodMinSize": strData(null, "Tamaño mínimo comida"),
        "foodMinAmount": strData(null, "Celdas mínimas en el mapa"),
        "virusMinSize": strData(null, "Tamaño mínimo de virus"),
        "virusMinAmount": strData(null, "Número mínimo de virus en el mapa"),
        "speedBoosterMinAmount": strData(null, "Cantidad poderes de velocidad"),
        "speedBoosterTime": strData(null, "Cuanto tiempo va a funcionar"),
        "speedBoosterValue": strData(null, "Multiplicador de velocidad (1.5 = 50% rápido, 0.5 = 50% lento"),
        "speedBoosterSize": strData(null, "Tamaño poder"),
        "mergeBoosterMinAmount": strData(null, "Número de poderes de unión"),
        "mergeBoosterTime": strData(null, "Cuanto tiempo va a funcionar"),
        "mergeBoosterValue": strData(null, "Multiplicador de tiempo de unión (0.5 = 50% rápido, 1.5 = 50% lento)"),
        "mergeBoosterSize": strData(null, "Tamaño poder"),
        "virusBoosterMinAmount": strData(null, "Cantidad poder de virus"),
        "virusBoosterTime": strData(null, "Cuanto tiempo va a funcionar"),
        "virusBoosterSize": strData(null, "Tamaño poder"),
        "sizeBoosterMinAmount": strData(null, "Cantidad poder de tamaño"),
        "sizeBoosterTime": strData(null, "Cuanto tiempo va a funcionar"),
    },
    // fr: {},
    tr: {
        "playerStartMass": strData(null, "oyuncu başlangıç kütlesi"),
        "playerMaxCells": strData(null, "oyuncu'nun parça limiti"),
        "playerSpeed": strData(null, "oyuncu'nun hızının katlanmsı (1=normal speed, 2=twice faster)"),
        "playerDecayRate": strData(null, "bır saniye içinde kaybedilen kütle"),
        "playerRecombineTime": strData(null, "parçanın yeniden birleşmesi için ayarlanan zaman"),
        "ejectSize": strData(null, "yem hacmi"),
        "ejectSizeLoss": strData(null, "oyuncudan eksilecek olan yem'in hacmi "),
        "ejectDistance": strData(null, "yemi'n fırlayacağı uzaklık"),
        "ejectCooldown": strData(null, "atılan yemlerin arasındakı zaman farkı (1 tick = 40 ms)"),
        "foodMinSize": strData(null, "Minimum yemek hacmi "),
        "foodMinAmount": strData(null, "harita üzerinde dağılan Minimum yemek parçaları"),
        "virusMinSize": strData(null, "Minimum virüs hacmi"),
        "virusMinAmount": strData(null, "Minimum virüs sayısı"),
        "speedBoosterMinAmount": strData(null, "hız"),
        "speedBoosterTime": strData(null, "hız desteğinin zamanı"),
        "speedBoosterValue": strData(null, "hız desteğinin gücü (1.5 = 50% faster, 0.5 = 50% slower"),
        "speedBoosterSize": strData(null, "hız desteğinin hacmi"),
        "mergeBoosterMinAmount": strData(null, "merge desteğinin sayısı"),
        "mergeBoosterTime": strData(null, "merge desteğinin zamanı"),
        "mergeBoosterValue": strData(null, "merge desteğinin gücü (0.5 = 50% faster, 1.5 = 50% slower)"),
        "mergeBoosterSize": strData(null, "merge desteğinin hacmi"),
        "virusBoosterMinAmount": strData(null, "virüs desteğinin sayısı"),
        "virusBoosterTime": strData(null, "virüs desteğinin zamanı"),
        "virusBoosterSize": strData(null, "virüs desteğinin hacmi"),
        "sizeBoosterMinAmount": strData(null, "hacim desteğinin sayısı"),
        "sizeBoosterTime": strData(null, "hacim desteğinin zamanı"),
    },
    pt: {
        "playerStartMass": strData(null, "Massa inicial dos jogadores"),
        "playerMaxCells": strData(null, "Máximo de células que um jogador pode ter"),
        "playerSpeed": strData(null, "Velocidade para multiplicar-se (1=velocidade normal, 2=2x mais rápido)"),
        "playerDecayRate": strData(null, "Tamanho perdido por segundo"),
        "playerRecombineTime": strData(null, "Tempo base para se juntar"),
        "ejectSize": strData(null, "Tamanho da ejeção"),
        "ejectSizeLoss": strData(null, "Tamanho da ejeção que será retirado do blob dos jogadores"),
        "ejectDistance": strData(null, "Até onde seu ejeto vai depois da divisão"),
        "ejectCooldown": strData(null, "Contagem até um jogador ejetar massa novamente (1 tick = 40 ms)"),
        "foodMinSize": strData(null, "Tamanho mínimo da comida"),
        "foodMinAmount": strData(null, "Células mínimas no mapa"),
        "virusMinSize": strData(null, "Tamanho mínimo do vírus"),
        "virusMinAmount": strData(null, "Número mínimo dos vírus no mapa"),
        "speedBoosterMinAmount": strData(null, "Quantidade dos poderes de velocidade"),
        "speedBoosterTime": strData(null, "Por quanto tempo funcionará"),
        "speedBoosterValue": strData(null, "Multiplicador de velocidade (1.5 = 50% rápido, 0.5 = 50% lento"),
        "speedBoosterSize": strData(null, "Tamanho do poder"),
        "mergeBoosterMinAmount": strData(null, "Quantidade dos poderes de junção"),
        "mergeBoosterTime": strData(null, "Por quanto tempo funcionará"),
        "mergeBoosterValue": strData(null, "Multiplicador do tempo de recombinação (0.5 = 50% rápido, 1.5 = 50% lento)"),
        "mergeBoosterSize": strData(null, "Tamanho do poder"),
        "virusBoosterMinAmount": strData(null, "Quantidade do poder de vírus"),
        "virusBoosterTime": strData(null, "Por quanto tempo funcionará"),
        "virusBoosterSize": strData(null, "Tamanho do poder"),
        "sizeBoosterMinAmount": strData(null, "Quantidade do poder de tamanho"),
        "sizeBoosterTime": strData(null, "Por quanto tempo funcionará"),
    },
    // de: {},
}

function strData(name, desc) {
    return {
        n: name,
        d: desc
    }
}

module.exports = CONFIG_NAMES;
